Fix: App crashing right after launch
Error: SwiftDataError(_error: SwiftData.SwiftDataError._Error.loadIssueModelContainer, _explanation: nil)

SwiftData models are configured to store data in iCloud, it requires model classes to have inverse relationships, but 'Session' did not have them with 'Task'.